[project]
name = "oilcompaniesexploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # "altair>=5.5.0",
    "plotly>=5.24.1",
    "polars>=1.14.0",
    "pyarrow>=18.0.0",
    "streamlit>=1.40.1",
]
